version: '3.8'

services:
  sample-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=development
      - PORT=5050
    volumes:
      - .:/app  # Для development режима
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "workshop=qa-devops"
      - "component=sample-app"

# Дополнительные сервисы для демонстрации
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sample-app
    labels:
      - "workshop=qa-devops"  
      - "component=reverse-proxy"

